### ISSUE TITLE
error AC1000: Unknown build error: System.NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by PatrickHofman** [tunnelvisionlabs/antlr4cs#243]
When compiling a project containing a grammar on Visual Studio for Mac, I get this error message:

> error AC1000: Unknown build error: System.NullReferenceException: Object reference not set to an instance of an object

The call stack is:

```
Target Antlr4Compile:
    Executing command: "/private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/../tools/net45/Antlr4.exe" -o obj/Debug/ -encoding UTF-8 -listener -visitor -Dlanguage=CSharp -package My.Sql /private/var/root/ws/mypackage/My.Data/Sql/SQL.g4 /private/var/root/ws/mypackage/My.Data/Sql/SQLTokens.g4
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: can't Load group file /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/tools/net45/Tool/Templates/Codegen/CSharp/CSharp_v4_5.stg
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Caused by: Object reference not set to an instance of an object
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Misc.TemplateRuntimeMessage..ctor (Antlr4.StringTemplate.Misc.ErrorType error, System.Int32 ip, Antlr4.StringTemplate.TemplateFrame frame, System.Exception e, System.Object arg, System.Object arg2) [0x00007] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Misc.TemplateRuntimeMessage..ctor (Antlr4.StringTemplate.Misc.ErrorType error, System.Int32 ip, Antlr4.StringTemplate.TemplateFrame frame, System.Exception e, System.Object arg) [0x00000] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Misc.ErrorManager.RuntimeError (Antlr4.StringTemplate.TemplateFrame frame, Antlr4.StringTemplate.Misc.ErrorType error, System.Exception e, System.Object arg) [0x00013] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.TemplateGroupFile.get_RootDirUri () [0x00021] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.TemplateGroup.ImportTemplates (Antlr.Runtime.IToken fileNameToken) [0x00055] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Compiler.GroupParser.group (Antlr4.StringTemplate.TemplateGroup group, System.String prefix) [0x00132] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.TemplateGroup.LoadGroupFile (System.String prefix, System.String fileName) [0x0008a] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: can't Load group file /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/tools/net45/Tool/Templates/Codegen/CSharp/CSharp_v4_5.stg
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Caused by: Object reference not set to an instance of an object
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Misc.TemplateRuntimeMessage..ctor (Antlr4.StringTemplate.Misc.ErrorType error, System.Int32 ip, Antlr4.StringTemplate.TemplateFrame frame, System.Exception e, System.Object arg, System.Object arg2) [0x00007] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Misc.TemplateRuntimeMessage..ctor (Antlr4.StringTemplate.Misc.ErrorType error, System.Int32 ip, Antlr4.StringTemplate.TemplateFrame frame, System.Exception e, System.Object arg) [0x00000] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Misc.ErrorManager.RuntimeError (Antlr4.StringTemplate.TemplateFrame frame, Antlr4.StringTemplate.Misc.ErrorType error, System.Exception e, System.Object arg) [0x00013] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.TemplateGroupFile.get_RootDirUri () [0x00021] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.TemplateGroup.ImportTemplates (Antlr.Runtime.IToken fileNameToken) [0x00055] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.Compiler.GroupParser.group (Antlr4.StringTemplate.TemplateGroup group, System.String prefix) [0x00132] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.StringTemplate.TemplateGroup.LoadGroupFile (System.String prefix, System.String fileName) [0x0008a] in <3f8c237f3f0f4e919fecc046951e5b22>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Unhandled Exception:
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: System.NullReferenceException: Object reference not set to an instance of an object
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.AbstractTarget.GetRecognizerFileName (System.Boolean header) [0x00022] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.CodeGenerator.GetRecognizerFileName (System.Boolean header) [0x00015] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.OutputModelController.BuildLexerOutputModel (System.Boolean header) [0x0000c] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.CodeGenerator.GenerateLexer (System.Boolean header) [0x00007] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.CodeGenPipeline.Process () [0x00115] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.ProcessNonCombinedGrammar (Antlr4.Tool.Grammar g, System.Boolean gencode) [0x000c2] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.Process (Antlr4.Tool.Grammar g, System.Boolean gencode) [0x000ba] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.ProcessGrammarsOnCommandLine () [0x00062] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.Main (System.String[] args) [0x00014] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: [ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.AbstractTarget.GetRecognizerFileName (System.Boolean header) [0x00022] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.CodeGenerator.GetRecognizerFileName (System.Boolean header) [0x00015] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.OutputModelController.BuildLexerOutputModel (System.Boolean header) [0x0000c] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.CodeGenerator.GenerateLexer (System.Boolean header) [0x00007] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.Codegen.CodeGenPipeline.Process () [0x00115] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.ProcessNonCombinedGrammar (Antlr4.Tool.Grammar g, System.Boolean gencode) [0x000c2] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.Process (Antlr4.Tool.Grammar g, System.Boolean gencode) [0x000ba] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.ProcessGrammarsOnCommandLine () [0x00062] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
    /private/var/root/ws/mypackage/packages/Antlr4.CodeGenerator.4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error:   at Antlr4.AntlrTool.Main (System.String[] args) [0x00014] in <41572b1990f84ca19e2bc9202ebd76d7>:0 
Done building target "Antlr4Compile" in project "My.Data.csproj" -- FAILED.

```
I have updated ANTLR to the Antlr4.CodeGenerator.4.6.5-beta001 version to get support for generating on the Mac, and I use the new C# implemented code generator using the instructions found here: https://github.com/tunnelvisionlabs/antlr4cs/releases/tag/v4.6.5-beta001.

Is this my fault? How can I fix this?

**Comment by sharwell** [comment]
This appears to be related to dotnet/corefx#1745. I probably should do a better job either in the ANTLR 4 Tool or in StringTemplate 4 of using URIs, but it appears that the underlying issue is resolved by .NET Core 2.0. Can you try using `dotnet build` (from release 2.0) instead of Visual Studio for Mac to compile the project, and let me know if it works in that scenario? I'll try to come up with a way to fix and test the case in general.

**Comment by PatrickHofman** [comment]
I have moved now to use .NET Standard on Windows. The Mac gave me too many issues. I am not too familiar to building from the command line on Mac, so I will dive into that and let you know if that worked.

**Comment by jpwiddy** [comment]
I still have this issue, upgraded to the beta version 001 as well.

```
/Users/usr/.nuget/packages/antlr4.codegenerator/4.6.5-beta001/build/Antlr4.CodeGenerator.targets(121,5): error AC1000: Unknown build error: Object reference not set to an instance of an object. 
[/Users/usr/Developer/IFS/Titanium/FSM.WebClient/FSM.WebClient.csproj]
```
This is using dotnet cli and .NET Core 2.0

**Comment by sharwell** [comment]
@jpwiddy thanks for letting me know!

**Comment by kevin-work** [comment]
So does this not build on non-Windows machines?
